# =========================================
#         McDis-RCON Configuration
# =========================================

### Application designed to stream the Minecraft console to Discord.
### This application is intended to work on Linux systems. (Tested on Ubuntu 22.04.3 LTS)
### While it may run on Windows, some features may not work as expected.
### To apply any changes, you must restart McDis!


### Description   : The bot token that will be used to initialize McDis.
### Advice        : Use a dedicated bot for McDis.
Bot Token: # BOT TOKEN

### Description   : The ID of the channel where the McDis panel will be created.
### Advice        : Use a clean channel for the McDis panel.
Panel ID: # CHANNEL ID

### Description   : Language that McDis will use.
### Valid Values  : [en, es]
### Default Value : en
Language: es

### Description   : Number of backups that McDis will save.
### Valid Values  : [1, 5] (inclusive)
### Default Value : 3
Backups: 3

### Description   : Flask configuration.
Flask:
  Allow : false
  IP    : '0.0.0.0'
  Port  : 8000

### Description   : Defines the processes managed by McDis.
###                 These include Minecraft servers (e.g., Vanilla, Fabric, Paper)
###                 and networks (e.g., Waterfall, Bungeecord, Velocity).

### • start_cmd   : Command to start the process. e.g.: java -Xms6G -Xmx6G -Dfile.encoding=UTF-8 -jar <launcher>.jar nogui
### • stop_cmd    : Command to stop the process.
### • blacklist   : List of terms; logs containing these terms will not be sent to Discord.

### Note: For MCDReforged users, ensure 'advanced_console' is set to False in the MCDR configuration.

Processes:
  Networks: 
    Waterfall:
      start_cmd: java -Dfile.encoding=UTF-8 -jar launcher.jar nogui
      stop_cmd: end
      blacklist: 
        - '<->'
        - '<-'
        - '->'

  Servers:
    SMP:
      start_cmd: python3 -m mcdreforged
      stop_cmd: stop
      blacklist: 
        - 'Changed the block at'
        - 'Successfully filled'
        - 'WARN]:'
        - 'No player was found'
        - '~[server-intermediary.jar:?]'
    
    CMP:
      start_cmd: python3 -m mcdreforged
      stop_cmd: stop
      blacklist: 
        - 'Changed the block at'
        - 'Successfully filled'
        - 'WARN]:'
        - 'No player was found'
        - '~[server-intermediary.jar:?]'
        
    MMP:
      start_cmd: python3 -m mcdreforged
      stop_cmd: stop
      blacklist: 
        - 'Changed the block at'
        - 'Successfully filled'
        - 'WARN]:'
        - 'No player was found'
        - '~[server-intermediary.jar:?]'
        
    PMP:
      start_cmd: python3 -m mcdreforged
      stop_cmd: stop
      blacklist: 
        - 'Changed the block at'
        - 'Successfully filled'
        - 'WARN]:'
        - 'No player was found'
        - '~[server-intermediary.jar:?]'
